cart/urls.py
"""拷贝过来的
"""
from django.urls import path

app_name = '[cart]'
urlpatterns = [

]

dailyfresh/urls.py
from django.contrib import admin
from django.urls import path, include
from dailyfresh.settings import BASE_DIR
from django.shortcuts import render

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("login.urls", namespace="login")),
    path("login.html", include("login.urls", namespace="login")),
    path("order/", include("order.urls", namespace="order")),
    path("user/", include("user.urls", namespace="user")),
    path("cart/", include("cart.urls", namespace="cart")),
    path("login/", include("login.urls", namespace="login")),
    path("tinymce/", include("tinymce.urls")),  # 富文本编辑器
    path("product/", include("product.urls", namespace="product")),

]

login/urls.py
"""拷贝过来的
"""
from django.urls import path, re_path
from django.conf.urls import url
from login.views import LoginView, ActiveView, RegisterView, ErrorView, LogoutView, ForgotPassWord, test

app_name = '[login]'
urlpatterns = [
    path("", LoginView.as_view()),
    path("register", RegisterView.as_view(), name="register"),
    path("register.html", RegisterView.as_view()),
    re_path("active/(?P<token>.*)", ActiveView.as_view(), name="active"),
    path("", LoginView.as_view(), name="login"),
    path("error.html", ErrorView.as_view(), name="error"),
    path("loginout", LogoutView.as_view(), name="logout"),
    path("test", test),
    url(r"^logout$", LoginView.as_view(), name="logout"),
    path("forgotPassword", ForgotPassWord.as_view(), name="forgotPassword")
]

user/urls.py
"""拷贝过来的
"""
from django.urls import path
from django.contrib.auth.decorators import login_required
from . import views

app_name = '[user]'
urlpatterns = [
    path("userinfo", login_required(views.UserInfoView.as_view()), name="userinfo"),
    path("useraddress", login_required(views.UserAddressView.as_view()), name="useraddress")
]

cart/models.py
from django.db import models

# Create your models here.

login/models.py
from django.db import models

# Create your models here.

cart/views.py
from django.shortcuts import render

# Create your views here.

login/views.py
from django.shortcuts import render, redirect, reverse
from user.models import User
from django.views.generic import View
from django.http import HttpResponse
from django.core.mail import send_mail
from django.contrib.auth import authenticate, login, logout
from django.conf import settings
from celery_tasks.tasks import send_register_active_email
from itsdangerous import TimedJSONWebSignatureSerializer as Serializer
from itsdangerous import SignatureExpired
import re
import logging


# Create your views here.


def test(request):
    return render(request, "test.html")


# def login(request):
#     if request.method == "POST":
#         username = request.POST.get("username")
#         pwd = request.POST.get("pwd")
#         user = User.objects.get(username=username)
#         if user is None or user.password != pwd:
#             return render(request, "index.html", {"magess": "用户名或密码不正确"})
#         return render(request, "index.html")
#     elif request.method == "GET":
#         return render(request, "login.html")
#     else:
#         return render(request, "404.html")

class LoginView(View):
    """登录"""

    def post(self, request):
        username = request.POST.get("username")
        pwd = request.POST.get("pwd")
        print("username=", username, "pwd=", pwd)
        if not all([username, pwd]):
            return render(request, "login.html", {"message": "用户名和密码都不能为空"})
        user = authenticate(username=username, password=pwd)
        if user is not None:
            if user.is_active:
                # 用户已经激活，记录用户的登录状态
                login(request, user)
                # 跳转到首页
                response = redirect((reverse("product:index")))
                # 判断是否需要记住用户名
                remember = request.POST.get("remember")
                print("remember=", remember)
                if remember == "on":
                    response.set_cookie("username", username, max_age=7 * 24 * 3600)
                else:
                    response.delete_cookie("username")
                # 返回response
                return response
            else:
                return render(request, "login.html", {"message": "用户未激活。"})
        else:
            return render(request, "login.html", {"message": "用户名或密码不正确。"})

    def get(self, request):
        print("进入登录页面。。。")
        # 判断是否记住了用户名
        if "username" in request.COOKIES:
            username = request.COOKIES.get("username")
            checked = "checked"
        else:
            username = ""
            checked = ""
        return render(request, "login.html", {"username": username, "checked": checked})


class LogoutView(View):
    def get(self, request):
        logout(request)
        return render(request, "login.html")


# def register(request):
#     if request.method == "POST":
#         body = request.POST
#         username = body.get("user_name")
#         pwd = body.get("pwd")
#         cpwd = body.get("cpwd")
#         email = body.get("email")
#         allow = body.get("allow")
#         if not all([username, pwd, cpwd, email, allow]):
#             return render(request, "register.html", {"status": -200, "massage": "数据不完整"})
#         # 校验邮箱
#         if not re.match(r"^[a-z0-9][\w.\-]*@[a-z0-9\-]+(\.[a-z]{2,5}){1,2}$", email):
#             return render(request, "register.html", {"status": -200, "massage": "邮箱格式不正确"})
#         if pwd != cpwd:
#             return render(request, "register.html", {"status": -200, "message": "密码不一致"})
#         if allow is None:
#             return render(request, "register.html", {"status": -200, "massage": "请同意协议！"})
#         # user = User()
#         # user.username = username
#         # user.password = pwd
#         # user.email = email
#         # user.is_active = True
#         # user.save()
#         try:
#             user = User.objects.get(username=username)
#         except User.DoesNotExist:
#             user = None
#         if user:
#             return render(request, "register.html", {"status": -200, "massage": "该用户已存在"})
#         user = User.objects.create_user(username, email, pwd)
#         user.is_active = 0
#         user.save()
#
#         # 加密用户的身份证，生成token
#         serializer = Serializer(settings.SECRET_KEY, 3600)
#         info = {"confirm": user.id}
#         token = serializer.dumps(info)  # byte
#         token = token.decode()
#         # 同步发邮件1-
#         # subject = "天天生鲜欢迎信息"
#         # message = ""
#         # sender = settings.EMAIL_FROM
#         # receivers = [email]
#         # html_message = "<h1>%s,欢迎您成为天天生鲜注册会员</h1>请点击下面链接激活您的的账号<br/><a href='http://127.0.0.1:8000/login/active/%s'>http://127.0.0.1:8000/login/active/%s</a>" % (
#         #     username, token, token)
#         # # 这里此方法是同步发送的，可能由于网络IO 引起 阻塞卡顿
#         # send_mail(subject, message, sender, receivers, html_message=html_message)
#         # 异步发邮件-2
#         send_register_active_email.delay(email, username, token)
#         return redirect(reverse("product:index"))
#     elif request.method == "GET":
#         print("register get...")
#         return render(request, "register.html")
#     else:
#         return render(request, "404.html")

class ForgotPassWord(View):
    """忘记密码"""

    def get(self, request):
        print("hello forgot html...")
        return render(request, "forgotPassword.html")

    def post(self, requeste):
        pass


class RegisterView(View):
    # 类视图使用
    def get(self, request):
        return render(request, "register.html")

    def post(self, request):
        body = request.POST
        username = body.get("user_name")
        pwd = body.get("pwd")
        cpwd = body.get("cpwd")
        email = body.get("email")
        allow = body.get("allow")
        if not all([username, pwd, cpwd, email, allow]):
            return render(request, "register.html", {"status": -200, "massage": "数据不完整"})
        # 校验邮箱
        if not re.match(r"^[a-z0-9][\w.\-]*@[a-z0-9\-]+(\.[a-z]{2,5}){1,2}$", email):
            return render(request, "register.html", {"status": -200, "massage": "邮箱格式不正确"})
        if pwd != cpwd:
            return render(request, "register.html", {"status": -200, "message": "密码不一致"})
        if allow is None:
            return render(request, "register.html", {"status": -200, "massage": "请同意协议！"})
        # user = User()
        # user.username = username
        # user.password = pwd
        # user.email = email
        # user.is_active = True
        # user.save()
        try:
            user = User.objects.get(username=username)
        except User.DoesNotExist:
            user = None
        if user:
            return render(request, "register.html", {"status": -200, "massage": "该用户已存在"})
        user = User.objects.create_user(username, email, pwd)
        user.is_active = 0
        user.save()

        # 加密用户的身份证，生成token
        serializer = Serializer(settings.SECRET_KEY, 3600)
        info = {"confirm": user.id}
        token = serializer.dumps(info)  # byte
        token = token.decode()
        # 同步发邮件1-
        # subject = "天天生鲜欢迎信息"
        # message = ""
        # sender = settings.EMAIL_FROM
        # receivers = [email]
        # html_message = "<h1>%s,欢迎您成为天天生鲜注册会员</h1>请点击下面链接激活您的的账号<br/><a href='http://127.0.0.1:8000/login/active/%s'>http://127.0.0.1:8000/login/active/%s</a>" % (
        #     username, token, token)
        # # 这里此方法是同步发送的，可能由于网络IO 引起 阻塞卡顿
        # send_mail(subject, message, sender, receivers, html_message=html_message)
        # 异步发邮件-2
        send_register_active_email.delay(email, username, token)
        return redirect(reverse("product:index"))


class ActiveView(View):
    """用户激活"""

    def get(self, request, token):
        """用户激活"""
        print("token=", token)
        # 解密
        serializer = Serializer(settings.SECRET_KEY, 3600)
        try:
            info = serializer.loads(token)
            # 获取待激活的用户id
            user_id = info["confirm"]
            print("user_id==", user_id)
            user = User.objects.get(id=user_id)
            user.is_active = 1
            user.save()
            # 跳转到登录页面
            return redirect(reverse("login:login"))
        except SignatureExpired as e:
            # 激活链接已经过期
            return HttpResponse("激活链接已经过期")


class ErrorView(View):
    def get(self, request):
        return render(request, "404.html")

templates/index.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
{% load staticfiles %}
<head>
    <meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
    <title>天天生鲜-首页</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
    <script type="text/javascript" src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/jquery-ui.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/slide.js' %}"></script>
</head>
<body>
<div class="header_con">
    <div class="header">
        <div class="welcome fl">欢迎来到天天生鲜!</div>
        <div class="fr">
            {% if user.is_authenticated %}
                <div class="login_btn fl">
                    欢迎您：<em>{{ user.username }}</em>
                    <span>|</span>
                    <a href="{% url 'login:logout' %}">退出</a>
                </div>
            {% else %}
                <div class="login_btn fl">
                    <a href="login.html">登录</a>
                    <span>|</span>
                    <a href="register.html">注册</a>
                </div>
            {% endif %}
            <div class="user_link fl">
                <span>|</span>
                <a href="{% url 'user:userinfo' %}">用户中心</a>
                <span>|</span>
                <a href="cart.html">我的购物车</a>
                <span>|</span>
                <a href="user_center_order.html">我的订单</a>
            </div>
        </div>
    </div>
</div>

<div class="search_bar clearfix">
    <a href="index.html" class="logo fl"><img src="../static/images/logo.png"></a>
    <div class="search_con fl">
        <input type="text" class="input_text fl" name="" placeholder="搜索商品">
        <input type="button" class="input_btn fr" name="" value="搜索">
    </div>
    <div class="guest_cart fr">
        <a href="#" class="cart_name fl">我的购物车</a>
        <div class="goods_count fl" id="show_count">1</div>
    </div>
</div>

<div class="navbar_con">
    <div class="navbar">
        <h1 class="fl">全部商品分类</h1>
        <ul class="navlist fl">
            <li><a href="">首页</a></li>
            <li class="interval">|</li>
            <li><a href="">手机生鲜</a></li>
            <li class="interval">|</li>
            <li><a href="">抽奖</a></li>
        </ul>
    </div>
</div>

<div class="center_con clearfix">
    <ul class="subnav fl">
        <li><a href="#model01" class="fruit">新鲜水果</a></li>
        <li><a href="#model02" class="seafood">海鲜水产</a></li>
        <li><a href="#model03" class="meet">猪牛羊肉</a></li>
        <li><a href="#model04" class="egg">禽类蛋品</a></li>
        <li><a href="#model05" class="vegetables">新鲜蔬菜</a></li>
        <li><a href="#model06" class="ice">速冻食品</a></li>
    </ul>
    <div class="slide fl">
        <ul class="slide_pics">
            <li><img src="../static/images/slide.jpg" alt="幻灯片"></li>
            <li><img src="../static/images/slide02.jpg" alt="幻灯片"></li>
            <li><img src="../static/images/slide03.jpg" alt="幻灯片"></li>
            <li><img src="../static/images/slide04.jpg" alt="幻灯片"></li>
        </ul>
        <div class="prev"></div>
        <div class="next"></div>
        <ul class="points"></ul>
    </div>
    <div class="adv fl">
        <a href="#"><img src="../static/images/adv01.jpg"></a>
        <a href="#"><img src="../static/images/adv02.jpg"></a>
    </div>
</div>

<div class="list_model">
    <div class="list_title clearfix">
        <h3 class="fl" id="model01">新鲜水果</h3>
        <div class="subtitle fl">
            <span>|</span>
            <a href="#">鲜芒</a>
            <a href="#">加州提子</a>
            <a href="#">亚马逊牛油果</a>
        </div>
        <a href="#" class="goods_more fr" id="fruit_more">查看更多 ></a>
    </div>

    <div class="goods_con clearfix">
        <div class="goods_banner fl"><img src="../static/images/banner01.jpg"></div>
        <ul class="goods_list fl">
            <li>
                <h4><a href="#">草莓</a></h4>
                <a href="#"><img src="../static/images/goods/goods003.jpg"></a>
                <div class="prize">¥ 30.00</div>
            </li>
            <li>
                <h4><a href="#">葡萄</a></h4>
                <a href="#"><img src="../static/images/goods/goods002.jpg"></a>
                <div class="prize">¥ 5.50</div>
            </li>
            <li>
                <h4><a href="#">柠檬</a></h4>
                <a href="#"><img src="../static/images/goods/goods001.jpg"></a>
                <div class="prize">¥ 3.90</div>
            </li>
            <li>
                <h4><a href="#">奇异果</a></h4>
                <a href="#"><img src="../static/images/goods/goods012.jpg"></a>
                <div class="prize">¥ 25.80</div>
            </li>
        </ul>
    </div>
</div>

<div class="list_model">
    <div class="list_title clearfix">
        <h3 class="fl" id="model02">海鲜水产</h3>
        <div class="subtitle fl">
            <span>|</span>
            <a href="#">河虾</a>
            <a href="#">扇贝</a>
        </div>
        <a href="#" class="goods_more fr">查看更多 ></a>
    </div>

    <div class="goods_con clearfix">
        <div class="goods_banner fl"><img src="../static/images/banner02.jpg"></div>
        <ul class="goods_list fl">
            <li>
                <h4><a href="#">青岛野生海捕大青虾</a></h4>
                <a href="#"><img src="../static/images/goods/goods018.jpg"></a>
                <div class="prize">¥ 48.00</div>
            </li>
            <li>
                <h4><a href="#">扇贝</a></h4>
                <a href="#"><img src="../static/images/goods/goods019.jpg"></a>
                <div class="prize">¥ 46.00</div>
            </li>
            <li>
                <h4><a href="#">冷冻秋刀鱼</a></h4>
                <a href="#"><img src="../static/images/goods/goods020.jpg"></a>
                <div class="prize">¥ 19.00</div>
            </li>
            <li>
                <h4><a href="#">基围虾</a></h4>
                <a href="#"><img src="../static/images/goods/goods021.jpg"></a>
                <div class="prize">¥ 25.00</div>
            </li>
        </ul>
    </div>
</div>

<div class="list_model">
    <div class="list_title clearfix">
        <h3 class="fl" id="model03">猪牛羊肉</h3>
        <div class="subtitle fl">
            <span>|</span>
            <a href="#">鲜芒</a>
            <a href="#">加州提子</a>
            <a href="#">亚马逊牛油果</a>
        </div>
        <a href="#" class="goods_more fr">查看更多 ></a>
    </div>

    <div class="goods_con clearfix">
        <div class="goods_banner fl"><img src="../static/images/banner03.jpg"></div>
        <ul class="goods_list fl">
            <li>
                <h4><a href="#">维多利亚葡萄维多利亚葡萄维多利亚葡萄维多利亚葡萄</a></h4>
                <a href="#"><img src="../static/images/goods.jpg"></a>
                <div class="prize">¥ 38.00</div>
            </li>
            <li>
                <h4><a href="#">维多利亚葡萄</a></h4>
                <a href="#"><img src="../static/images/goods.jpg"></a>
                <div class="prize">¥ 38.00</div>
            </li>
            <li>
                <h4><a href="#">维多利亚葡萄</a></h4>
                <a href="#"><img src="../static/images/goods.jpg"></a>
                <div class="prize">¥ 38.00</div>
            </li>
            <li>
                <h4><a href="#">维多利亚葡萄</a></h4>
                <a href="#"><img src="../static/images/goods.jpg"></a>
                <div class="prize">¥ 38.00</div>
            </li>
        </ul>
    </div>
</div>

<div class="list_model">
    <div class="list_title clearfix">
        <h3 class="fl" id="model04">禽类蛋品</h3>
        <div class="subtitle fl">
            <span>|</span>
            <a href="#">鲜芒</a>
            <a href="#">加州提子</a>
            <a href="#">亚马逊牛油果</a>
        </div>
        <a href="#" class="goods_more fr">查看更多 ></a>
    </div>

    <div class="goods_con clearfix">
        <div class="goods_banner fl"><img src="../static/images/banner04.jpg"></div>
        <ul class="goods_list fl">
            <li>
                <h4><a href="#">维多利亚葡萄维多利亚葡萄维多利亚葡萄维多利亚葡萄</a></h4>
                <a href="#"><img src="../static/images/goods.jpg"></a>
                <div class="prize">¥ 38.00</div>
            </li>
            <li>
                <h4><a href="#">维多利亚葡萄</a></h4>
                <a href="#"><img src="../static/images/goods.jpg"></a>
                <div class="prize">¥ 38.00</div>
            </li>
            <li>
                <h4><a href="#">维多利亚葡萄</a></h4>
                <a href="#"><img src="../static/images/goods.jpg"></a>
                <div class="prize">¥ 38.00</div>
            </li>
            <li>
                <h4><a href="#">维多利亚葡萄</a></h4>
                <a href="#"><img src="../static/images/goods.jpg"></a>
                <div class="prize">¥ 38.00</div>
            </li>
        </ul>
    </div>
</div>

<div class="list_model">
    <div class="list_title clearfix">
        <h3 class="fl" id="model05">新鲜蔬菜</h3>
        <div class="subtitle fl">
            <span>|</span>
            <a href="#">鲜芒</a>
            <a href="#">加州提子</a>
            <a href="#">亚马逊牛油果</a>
        </div>
        <a href="#" class="goods_more fr">查看更多 ></a>
    </div>

    <div class="goods_con clearfix">
        <div class="goods_banner fl"><img src="../static/images/banner05.jpg"></div>
        <ul class="goods_list fl">
            <li>
                <h4><a href="#">维多利亚葡萄维多利亚葡萄维多利亚葡萄维多利亚葡萄</a></h4>
                <a href="#"><img src="../static/images/goods.jpg"></a>
                <div class="prize">¥ 38.00</div>
            </li>
            <li>
                <h4><a href="#">维多利亚葡萄</a></h4>
                <a href="#"><img src="../static/images/goods.jpg"></a>
                <div class="prize">¥ 38.00</div>
            </li>
            <li>
                <h4><a href="#">维多利亚葡萄</a></h4>
                <a href="#"><img src="../static/images/goods.jpg"></a>
                <div class="prize">¥ 38.00</div>
            </li>
            <li>
                <h4><a href="#">维多利亚葡萄</a></h4>
                <a href="#"><img src="../static/images/goods.jpg"></a>
                <div class="prize">¥ 38.00</div>
            </li>
        </ul>
    </div>
</div>

<div class="list_model">
    <div class="list_title clearfix">
        <h3 class="fl" id="model06">速冻食品</h3>
        <div class="subtitle fl">
            <span>|</span>
            <a href="#">鲜芒</a>
            <a href="#">加州提子</a>
            <a href="#">亚马逊牛油果</a>
        </div>
        <a href="#" class="goods_more fr">查看更多 ></a>
    </div>

    <div class="goods_con clearfix">
        <div class="goods_banner fl"><img src="../static/images/banner06.jpg"></div>
        <ul class="goods_list fl">
            <li>
                <h4><a href="#">维多利亚葡萄维多利亚葡萄维多利亚葡萄维多利亚葡萄</a></h4>
                <a href="#"><img src="../static/images/goods.jpg"></a>
                <div class="prize">¥ 38.00</div>
            </li>
            <li>
                <h4><a href="#">维多利亚葡萄</a></h4>
                <a href="#"><img src="../static/images/goods.jpg"></a>
                <div class="prize">¥ 38.00</div>
            </li>
            <li>
                <h4><a href="#">维多利亚葡萄</a></h4>
                <a href="#"><img src="../static/images/goods.jpg"></a>
                <div class="prize">¥ 38.00</div>
            </li>
            <li>
                <h4><a href="#">维多利亚葡萄</a></h4>
                <a href="#"><img src="../static/images/goods.jpg"></a>
                <div class="prize">¥ 38.00</div>
            </li>
        </ul>
    </div>
</div>

<div class="footer">
    <div class="foot_link">
        <a href="#">关于我们</a>
        <span>|</span>
        <a href="#">联系我们</a>
        <span>|</span>
        <a href="#">招聘人才</a>
        <span>|</span>
        <a href="#">友情链接</a>
    </div>
    <p>CopyRight © 2016 北京天天生鲜信息技术有限公司 All Rights Reserved</p>
    <p>电话：010-****888 京ICP备*******8号</p>
</div>
<script type="text/javascript" src="{% static 'js/slide.js' %}"></script>
<script type="text/javascript">
    BCSlideshow('focuspic');
    var oFruit = document.getElementById('fruit_more');
    var oShownum = document.getElementById('show_count');

    var hasorder = localStorage.getItem('order_finish');

    if (hasorder) {
        oShownum.innerHTML = '2';
    }

    oFruit.onclick = function () {
        window.location.href = 'list.html';
    }
</script>
</body>
</html>

templates/login.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
{% load staticfiles %}
<head>
    <meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
    <title>天天生鲜-登录</title>
    <link rel="stylesheet" type="text/css" href="../static/css/reset.css">
    <link rel="stylesheet" type="text/css" href="../static/css/main.css">
</head>
<body>
<div class="login_top clearfix">
    <a href="index.html" class="login_logo"><img src="../static/images/logo02.png"></a>
</div>

<div class="login_form_bg">
    <div class="login_form_wrap clearfix">
        <div class="login_banner fl"></div>
        <div class="slogan fl">日夜兼程 · 急速送达</div>
        <div class="login_form fr">
            <div class="login_title clearfix">
                <h1>用户登录</h1>
                <a href="{% url  'login:register' %}">立即注册</a>
            </div>
            <div class="form_input">
                <form action="/login/" method="post">
                    {% csrf_token %}
                    <input type="text" name="username" value="{{ username }}" class="name_input" placeholder="请输入用户名">
                    <div class="user_error">输入错误</div>
                    <input type="password" name="pwd" class="pass_input" placeholder="请输入密码">
                    <div class="pwd_error">输入错误</div>
                    <div class="more_input clearfix">
                        <input type="checkbox" name="remember" {{ checked }}>
                        <label>记住用户名</label>
                        <a href="{% url 'login:forgotPassword' %}">忘记密码</a>
                    </div>
                    <input type="submit" name="" value="登录" class="input_submit">
                </form>
            </div>
            <h1 style="text-align: center;justify-items: center;color: red;margin-bottom: 10px;">{{ message }}</h1>
        </div>
    </div>
</div>

<div class="footer no-mp">
    <div class="foot_link">
        <a href="#">关于我们</a>
        <span>|</span>
        <a href="#">联系我们</a>
        <span>|</span>
        <a href="#">招聘人才</a>
        <span>|</span>
        <a href="#">友情链接</a>
    </div>
    <p>CopyRight © 2020 哒哒天天生鲜信息技术有限公司 All Rights Reserved</p>
    <p>电话：010-****888 深ICP备*******8号</p>
</div>

</body>
</html>

templates/register.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block title %}
    天天生鲜-注册
{% endblock title %}

{% block topfiles %}
    <script type="text/javascript" src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/register.js' %}"></script>
{% endblock topfiles %}

{% block header_con %}{% endblock header_con %}
{% block search_bar %}{% endblock search_bar %}
{% block body %}
    <div class="register_con">
        <div class="l_con fl">
            <a class="reg_logo"><img src="{% static 'images/logo02.png' %}"></a>
            <div class="reg_slogan">足不出户 · 新鲜每一天</div>
            <div class="reg_banner"></div>
        </div>

        <div class="r_con fr">

            <div class="reg_title clearfix">
                <h1>用户注册</h1>
                <a href="/login/">登录</a>
            </div>
            <div class="reg_form clearfix">
                <form action="{% url 'login:register' %}" method="post">
                    {% csrf_token %}
                    <ul>
                        <li>
                            <label>用户名:</label>
                            <input type="text" name="user_name" id="user_name">
                            <span class="error_tip">提示信息</span>
                        </li>
                        <li>
                            <label>密码:</label>
                            <input type="password" name="pwd" id="pwd">
                            <span class="error_tip">提示信息</span>
                        </li>
                        <li>
                            <label>确认密码:</label>
                            <input type="password" name="cpwd" id="cpwd">
                            <span class="error_tip">提示信息</span>
                        </li>
                        <li>
                            <label>邮箱:</label>
                            <input type="text" name="email" id="email">
                            <span class="error_tip">提示信息</span>
                        </li>
                        <li class="agreement">
                            <input type="checkbox" name="allow" id="allow" checked="checked">
                            <label>同意”天天生鲜用户使用协议“</label>
                            <span class="error_tip2">提示信息</span>
                        </li>
                        <li class="reg_sub">
                            <input type="submit" value="注 册" name="">
                        </li>
                        <li><span style="color: red;font-size: 15px">{{ massage }}</span></li>
                    </ul>
                </form>
            </div>

        </div>

    </div>
{% endblock body %}